# Configurações do banco de dados
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo-app
    username: postgres
    password: arthur22
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: your_secret_key
